version: "3.9"

services:
  db:
    image: postgres
    container_name: denvow_postgres_db
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=pass
    networks:
      - my_network

  web:
    build: .
    container_name: denvow_web
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=mydb
      - DB_USER=root
      - DB_PASSWORD=pass
      - DB_HOST=db
      - DB_PORT=5432

    depends_on:
      - db
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
